---
name: bosh-stemcell-smoke-tests

releases:
- name: syslog
  version: latest
- name: os-conf
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: ((stemcell_version))

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: immutable_audit_rules
  stemcell: default
  vm_type: default
  instances: 1
  networks:
  - {name: default}
  azs: [z1]
  jobs:
  - name: auditd
    release: os-conf

- name: syslog_storer
  stemcell: default
  vm_type: default
  instances: 1
  networks:
  - { name: dynamic_public,  default: [dns, gateway] }
  - { name: dynamic_private }
  azs: [z1]
  jobs:
  - name: syslog_storer
    release: syslog
    properties:
      syslog:
        transport: tcp
        port: 514

- name: syslog_forwarder
  stemcell: default
  vm_type: default
  azs: [z1]
  instances: 1
  networks:
  - { name: dynamic_public, default: [dns, gateway] }
  - { name: dynamic_private }
  jobs:
  - name: syslog_forwarder
    release: syslog
    consumes:
      syslog_storer: { from: syslog_storer }
