---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/compiled-release

inputs:
  - name: director-state
  - name: bosh-linux-stemcell-builder-master
  - name: bosh-linux-stemcell-builder

run:
  path: bosh-linux-stemcell-builder-master/ci/softlayer_ng/bats/tasks/destroy-director.sh
