---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-deployment
  - name: bosh-linux-stemcell-builder-master
  - name: stemcell
  - name: bosh-cli
  - name: environment

params:
  DEPLOY_ARGS: ""
  BAT_INFRASTRUCTURE: ""

outputs:
  - name: director-state

run:
  path: bosh-linux-stemcell-builder-master/ci/bluemix/bats/tasks/deploy-director-softlayer.sh

