---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/compiled-release

inputs:
  - name: bosh-linux-stemcell-builder
  - name: environment
  - name: director-state

params:
  STEMCELL_NAME: null

outputs:
  - name: bats-config

run:
  path: bosh-linux-stemcell-builder/ci/bats/iaas/vsphere/prepare-bats-config.sh
