---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/compiled-release}

inputs:
  - name: bosh-linux-stemcell-builder-master
  - name: bosh-linux-stemcell-builder
  - name: environment
  - name: director-state

params:
  STEMCELL_NAME: null
  BAT_VCAP_PASSWORD:      ""

outputs:
  - name: bats-config

run:
  path: bosh-linux-stemcell-builder-master/ci/softlayer_ng/bats/iaas/softlayer/prepare-bats-config.sh
