---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: published-stemcell
  - name: bosh-linux-stemcell-builder-master
outputs:
  - name: version
run:
  path: bosh-linux-stemcell-builder-master/ci/tasks/bluemix_ng/make-stemcell-version.sh
