---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-linux-stemcell-builder-master
  - name: director-state
  - name: bosh-cli

run:
  path: bosh-linux-stemcell-builder-master/ci/bluemix_ng/tasks/teardown.sh
