---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: published-stemcell
  - name: bosh-linux-stemcell-builder-master
outputs:
  - name: boshagent-version
run:
  path: bosh-linux-stemcell-builder-master/ci/softlayer/tasks/make-boshagent-version.sh
