---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ubuntu-chroot

inputs:
  - name: bosh-linux-stemcell-builder-master
  - name: bosh-linux-stemcell-builder

run:
  path: bosh-linux-stemcell-builder-master/ci/bluemix/tasks/test-unit.sh
