---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bluebosh/slcli_py

inputs:
  - name: version
  - name: bosh-linux-stemcell-builder

outputs:
  - name: stemcell-image
run:
  path: bosh-linux-stemcell-builder/ci/tasks/capture-stemcell.sh
