---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: bosh-linux-stemcell-builder
outputs:
  - name: version
run:
  path: bosh-linux-stemcell-builder/ci/custom_stemcell/tasks/customize-stemcell-version.sh
