---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bluebosh/slcli_py

inputs:
  - name: version
  - name: bosh-linux-stemcell-builder-master
    path: bosh-linux-stemcell-builder

run:
  path: bosh-linux-stemcell-builder/ci/custom_stemcell/tasks/deploy-vm-ded.sh

  