---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: zhanggongsw/bosh

inputs:
  - name: bosh-linux-stemcell-builder-master
  - name: stemcell-info
  - name: version
  - name: stemcell
outputs:
  - name: light-stemcell

run:
  path: bosh-linux-stemcell-builder-master/ci/xenial/tasks/create-light-stemcell.sh
