---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-publisher

inputs:
  - name: version
  - name: bosh-linux-stemcell-builder-master
    path: bosh-linux-stemcell-builder
  - name: stemcell
  - name: stemcells-index
outputs:
  - name: version-tag
  - name: stemcells-index
    path: stemcells-index-output

run:
  path: bosh-linux-stemcell-builder/ci/xenial/tasks/publish-stemcells-boshio.sh

params:
  PUBLISHED_BUCKET_NAME: required
  OS_NAME:               required
  OS_VERSION:            required
