---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
<<<<<<< HEAD
  - name: bosh-src
=======
>>>>>>> a08b526bd138f39e3aee76c58d31cb394301dc8b
  - name: bosh-linux-stemcell-builder
  - name: version

outputs:
  - name: stemcell

run:
  path: bosh-linux-stemcell-builder/ci/tasks/build-softlayer.sh

params:
  IAAS:         replace-me
  HYPERVISOR:   replace-me
  OS_NAME:      replace-me
  OS_VERSION:   replace-me
  BOSHIO_TOKEN: ""

