---
groups:
  - name: all
    jobs:
      - new-version-notification
      - test-unit
      - increment-version
      - new-stemcell-version
      - convert-softlayer-stemcell
      - import-softlayer-stemcell
      - create-softlayer-light-stemcell
      - publish-stemcells
      - post-stemcells
      - test-stemcells
      - build-softlayer-xen-ubuntu-trusty
      - bats-ubuntu
      - deploy-director
      - deploy-cf
      - update-dns
      - verify-cf

  - name: softlayer
    jobs:
      - build-softlayer-xen-ubuntu-trusty
      - convert-softlayer-stemcell
      - import-softlayer-stemcell
      - create-softlayer-light-stemcell

  - name: ubuntu
    jobs:
      - build-softlayer-xen-ubuntu-trusty

  - name: bats
    jobs:
      - bats-ubuntu

  - name: automation-cf
    jobs:
      - deploy-director
      - deploy-cf
      - update-dns
      - verify-cf

shared:
  - &deploy-director
    task: deploy-director
    file: bosh-linux-stemcell-builder-master/ci/softlayer/bats/tasks/deploy-director-softlayer.yml
    params:
      BAT_INFRASTRUCTURE:                   softlayer
      BOSH_CLIENT:                          {{stemcell-test-director-username}}
      BOSH_CLIENT_SECRET:                   {{stemcell-test-director-password}}
      BOSH_SL_USERNAME:                          {{softlayer-username}}
      BOSH_SL_API_KEY:                           {{softlayer-api-key}}
      BOSH_SL_DATACENTER:                        {{softlayer-datacenter}}
      BOSH_SL_VLAN_PUBLIC:                       {{softlayer-vlan-public}}
      BOSH_SL_VLAN_PRIVATE:                      {{softlayer-vlan-private}}
      BOSH_SL_VM_DOMAIN:                         {{softlayer-vm-domain}}
      BOSH_SL_VM_NAME_PREFIX:                    {{softlayer-director-name-prefix}}

  - &prepare-bats-config
    task: prepare-bats
    file: bosh-linux-stemcell-builder-master/ci/softlayer/bats/iaas/softlayer/prepare-bats-config.yml
    params: &prepare-bats-params
      BAT_VCAP_PASSWORD:      {{bat-vcap-password}}
      SL_DATACENTER:          {{softlayer-datacenter}}
      SL_VLAN_PRIVATE:        {{softlayer-vlan-private}}
      SL_VLAN_PUBLIC:         {{softlayer-vlan-public}}
      SL_VM_DOMAIN:           {{softlayer-vm-domain}}
      SL_VM_NAME_PREFIX:      {{softlayer-vm-name-prefix}}
      STEMCELL_NAME:          bosh-softlayer-xen-ubuntu-trusty-go_agent

  - &run-bats
    task: run-bats
    file: bats/ci/tasks/run-bats.yml

  - &teardown
    task: teardown
    file: bosh-linux-stemcell-builder-master/ci/softlayer/bats/tasks/destroy-director.yml

jobs:
  - name: new-version-notification
    plan:
      - get: published-stemcell
        trigger: true
      - get: bosh-linux-stemcell-builder-master
      - task: notice-new-version
        file: bosh-linux-stemcell-builder-master/ci/softlayer/tasks/notice-new-version.yml
        params:
          SLACK_URL:      {{slack_url}}

  - name: test-unit
    serial: true
    plan:
      - get: bosh-linux-stemcell-builder
        trigger: true
      - get: bosh-linux-stemcell-builder-master
      - task: test-unit
        file: bosh-linux-stemcell-builder-master/ci/softlayer/tasks/test-unit.yml

  - name: new-stemcell-version
    plan:
      - get: published-stemcell
      - get: bosh-linux-stemcell-builder-master
      - task: make-version
        file: bosh-linux-stemcell-builder-master/ci/softlayer/tasks/make-stemcell-version.yml
      - put: version
        params: {file: version/number}

  - name: increment-version
    serial: true
    plan:
      - get: version
        params:
          bump: patch
      - put: version
        params:
          file: version/number

  - name: test-stemcells
    serial: true
    plan:
      - aggregate:
        - get: version
          trigger: true
          passed:
            - create-softlayer-light-stemcell
        - get: bosh-linux-stemcell-builder-master
        - get: bosh-linux-stemcell-builder
        - get: bosh-deployment
        - get: bosh-cli
        - get: syslog-release
        - get: os-conf-release
        - get: light-softlayer-stemcell
          passed: [create-softlayer-light-stemcell]
        - put: environment
          params:
            acquire: true
      - do:
        - task: deploy-director
          file: bosh-linux-stemcell-builder-master/ci/softlayer/tasks/deploy-director-softlayer.yml
          input_mapping:
            stemcell: light-softlayer-stemcell
          params:
            SL_API_KEY: {{softlayer-api-key}}
            SL_USERNAME:  {{softlayer-username}}
            SL_VLAN_PRIVATE: {{softlayer-vlan-private}}
            SL_VLAN_PUBLIC: {{softlayer-vlan-public}}
            SL_VM_DOMAIN: softlayer.com
            SL_VM_NAME_PREFIX: {{softlayer-director-name-prefix}}
            SL_VM_NAME_PREFIX_2: {{softlayer-vm-name-prefix}}
            SL_PUBLIC_SSH_KEY: {{softlayer-public-ssh-key}}
        - task: test-stemcell
          file: bosh-linux-stemcell-builder-master/ci/softlayer/tasks/test-stemcell.yml
          input_mapping:
            stemcell: light-softlayer-stemcell
          params:
            BOSH_os_name: ubuntu-trusty
            package: ipv4director
        ensure:
          do:
          - task: teardown
            file: bosh-linux-stemcell-builder-master/ci/softlayer/tasks/teardown.yml
          - put: environment
            params:
              release: environment

  - name: publish-stemcells
    serial: true
    plan:
      - aggregate:
        - get: version
          passed:
            - bats-ubuntu
            - test-stemcells
            - verify-cf
        - get: bosh-linux-stemcell-builder-master
        - get: bosh-linux-stemcell-builder
        - get: stemcell
          trigger: true
          resource: light-softlayer-stemcell
          passed:
            - bats-ubuntu
      - task: copy-artifacts
        file: bosh-linux-stemcell-builder-master/ci/softlayer/tasks/copy-artifacts.yml
        params:
          AWS_ACCESS_KEY_ID: {{stemcell-aws-access-key}}
          AWS_SECRET_ACCESS_KEY: {{stemcell-aws-secret-key}}
          CANDIDATE_BUCKET_NAME: {{candidate-stemcell-bucket}}
      - put: light-softlayer-stemcell-prod
        params: {file: light-softlayer-stemcell-prod/*.tgz}
      - put: bosh-linux-stemcell-builder
        params: {repository: bosh-linux-stemcell-builder, tag: version-tag/tag, only_tag: true}

  - name: post-stemcells
    serial: true
    plan:
      - aggregate:
        - get: version
          passed:
            - publish-stemcells
        - get: stemcell
          resource: light-softlayer-stemcell-prod
          passed:
            - publish-stemcells
        - get: bosh-linux-stemcell-builder-master
        - get: stemcells-index
      - task: post-stemcell
        file: bosh-linux-stemcell-builder-master/ci/softlayer/tasks/post-stemcell.yml
        params:
          PUBLISHED_BUCKET_NAME: {{published-stemcell-bucket}}
          OS_NAME:               {{os_name}}
          OS_VERSION:            {{os_version}}
      - put: stemcells-index
        params:
          repository: stemcells-index

  #
  # SoftLayer
  #

  - name: build-softlayer-xen-ubuntu-trusty
    plan:
      - aggregate:
          - get: version
            trigger: true
          - get: bosh-linux-stemcell-builder-master
          - get: bosh-linux-stemcell-builder
      - task: create-stemcell
        file: bosh-linux-stemcell-builder-master/ci/softlayer/tasks/build-softlayer.yml
        privileged: true
        params:
          IAAS:         softlayer
          HYPERVISOR:   xen
          OS_NAME:      ubuntu
          OS_VERSION:   trusty
      - aggregate:
        - put: softlayer-xen-ubuntu-trusty
          params:
            file: stemcell/*.tgz

  - name: convert-softlayer-stemcell
    plan:
      - aggregate:
          - get: version
            trigger: false
            passed: [build-softlayer-xen-ubuntu-trusty]
          - get: bosh-softlayer-tools-master
          - get: softlayer-xen-ubuntu-trusty
            trigger: true
            passed: [build-softlayer-xen-ubuntu-trusty]
      - task: convert-stemcell
        file: bosh-softlayer-tools-master/ci/softlayer/tasks/convert-stemcell.yml
        params:
          IAAS:         softlayer
          HYPERVISOR:   xen
          OS_NAME:      ubuntu
          OS_VERSION:   trusty
          SWIFT_USERNAME:  {{swift-username}}
          SWIFT_API_KEY: {{softlayer-api-key}}
          SWIFT_CLUSTER:  {{swift-cluster}}
          SWIFT_CONTAINER: {{swift-container}}
        input_mapping:
          stemcell: softlayer-xen-ubuntu-trusty

  - name: import-softlayer-stemcell
    plan:
      - get: stemcell-cmds
      - get: bosh-softlayer-tools-master
      - get: bosh-softlayer-tools
      - get: version
        trigger: true
        passed: [convert-softlayer-stemcell]
      - task: import-stemcell-image
        file: bosh-softlayer-tools-master/ci/softlayer/tasks/import-stemcell.yml
        params:
          IAAS: softlayer
          HYPERVISOR: xen
          OS_NAME: ubuntu
          OS_VERSION: trusty
          SL_USERNAME: {{softlayer-username}}
          SL_API_KEY: {{softlayer-api-key}}
          SWIFT_USERNAME: {{swift-username}}
          SWIFT_API_KEY: {{softlayer-api-key}}
          SWIFT_CLUSTER: {{swift-cluster}}
          SWIFT_CONTAINER: {{swift-container}}
      - put: stemcell-info
        params: {file: stemcell-image/stemcell-info.json}

  - name: create-softlayer-light-stemcell
    plan:
      - aggregate:
        - get: stemcell-cmds
        - get: bosh-softlayer-tools-master
        - get: bosh-softlayer-tools
        - get: softlayer-xen-ubuntu-trusty
        - get: stemcell-info
          trigger: true
          passed: [import-softlayer-stemcell]
        - get: version
          trigger: true
          passed: [import-softlayer-stemcell]
      - task: create-light-stemcell
        file: bosh-softlayer-tools-master/ci/softlayer/tasks/create-light-stemcell.yml
        params:
          HYPERVISOR: xen
          IAAS: softlayer
          OS_NAME: ubuntu
          OS_VERSION: trusty
          STEMCELL_FORMATS: softlayer-light-legacy
          SL_USERNAME: {{softlayer-username}}
          SL_API_KEY: {{softlayer-api-key}}
        input_mapping:
          stemcell: softlayer-xen-ubuntu-trusty
      - put: light-softlayer-stemcell
        params: {file: light-stemcell/*.tgz}

  - name: bats-ubuntu
    serial: true
    plan:
    - do:
      - aggregate:
        - get: bosh-release
        - get: cpi-release
        - get: stemcell
          trigger: true
          resource: light-softlayer-stemcell
          passed:
            - create-softlayer-light-stemcell
        - get: bosh-cli
        - get: bats
        - get: bosh-deployment
        - get: bosh-linux-stemcell-builder
        - get: bosh-linux-stemcell-builder-master
        - get: version
          passed:
            - create-softlayer-light-stemcell

      - {put: environment, params: {acquire: true}}

      - do:
        - <<: *deploy-director

        - <<: *prepare-bats-config
          params:
            <<: *prepare-bats-params

        - <<: *run-bats
        ensure:
          do:
          - <<: *teardown
      ensure:
        do:
        - {put: environment, params: {release: environment}}

  - name: deploy-director
    serial: true
    plan:
    - aggregate:
      - get: version
        trigger: true
        passed: [create-softlayer-light-stemcell]
      - get: bosh-deployment
      - get: bosh-cli-v2
        resource: bosh-cli
      - get: bosh-linux-stemcell-builder-master
    - do:
      - task: deploy-dynamic-ip-director
        file: bosh-linux-stemcell-builder-master/ci/softlayer/auto-cf/deploy-director.yml
        params:
          INFRASTRUCTURE:                      softlayer
          SL_VM_PREFIX:                        {{softlayer-director-name-prefix}}
          SL_VM_DOMAIN:                        {{softlayer-vm-domain}}
          CF_PREFIX:                           {{softlayer-cf-prefix}}
          SL_USERNAME:                         {{softlayer-username}}
          SL_API_KEY:                          {{softlayer-api-key}}
          SL_DATACENTER:                       {{softlayer-datacenter}}
          SL_VLAN_PUBLIC:                      {{softlayer-vlan-public}}
          SL_VLAN_PRIVATE:                     {{softlayer-vlan-private}}
      - put: director-artifacts
        params:
          file: deploy-artifacts/director_artifacts.tgz

  - name: deploy-cf
    serial: true
    plan:
    - aggregate:
      - get: version
        trigger: true
        passed: [deploy-director]
      - get: director-artifacts
        passed: [deploy-director]
      - get: bosh-softlayer-tools
        resource: bosh-softlayer-tools-master
      - get: cf-deployment
        resource: cf-deployment-softlayer
      - get: bosh-linux-stemcell-builder-master
    - task: deploy-comunity-cf
      file: bosh-linux-stemcell-builder-master/ci/softlayer/auto-cf/deploy-cf.yml
      params:
        DEPLOYMENT_NAME:            {{deployment-name}}
        SYSTEM_DOMAIN:              {{cf_system_domain}}
    - put: cf-artifacts
      params:
        file: cf-artifacts/cf_artifacts.tgz


  - name: update-dns
    serial: true
    plan:
    - aggregate:
      - get: version
        trigger: true
        passed: [deploy-cf]
      - get: bosh-softlayer-tools
        resource: bosh-softlayer-tools-master
      - get: cf-artifacts-comm
        resource: cf-artifacts
        passed: [deploy-cf]
    - task: update-dns
      file: bosh-softlayer-tools/ci/cf_deployment_ng/tasks/community/update-dns.yml
      params:
        SYSTEM_DOMAIN:  {{cf_system_domain}}
    - put: cf-artifacts
      params:
        file: cf-artifacts/cf_artifacts.tgz

  - name: verify-cf
    serial: true
    plan:
      - aggregate:
        - get: version
          trigger: true
          passed: [update-dns]
        - get: bosh-softlayer-tools
          resource: bosh-softlayer-tools-master
        - get: cf-artifacts-comm
          resource: cf-artifacts
          passed: [update-dns]
        - get: director-artifacts
          resource: director-artifacts
      - do:
        - task: verify-cf-push
          file: bosh-softlayer-tools/ci/cf_deployment_ng/tasks/community/verify-cf.yml
          params: &cf-params
            SYSTEM_DOMAIN:  {{cf_system_domain}}
        - task: teardown
          file: bosh-softlayer-tools/ci/cf_deployment_ng/tasks/community/teardown.yml
          params:
            DEPLOYMENT_COMMUNITY_NAME: {{deployment-name}}

resources:
  - name: bosh-linux-stemcell-builder-master
    type: git
    source:
      uri: https://github.com/bluebosh/bosh-linux-stemcell-builder
      branch: master

  - name: bosh-linux-stemcell-builder
    type: git
    source:
      uri: git@github.com:bluebosh/bosh-linux-stemcell-builder
      branch: softlayer
      private_key: {{github_private_key}}

  - name: version
    type: semver
    source:
      driver: s3
      initial_version: {{stemcell_initial_version}}
      key: {{stemcell_version_key}}
      bucket: {{candidate-stemcell-bucket}}
      access_key_id: {{stemcell-aws-access-key}}
      secret_access_key: {{stemcell-aws-secret-key}}

  - name: stemcell-info
    type: s3
    source:
      bucket: {{candidate-stemcell-bucket}}
      access_key_id: {{stemcell-aws-access-key}}
      secret_access_key: {{stemcell-aws-secret-key}}
      versioned_file: stemcell-info.json

  - name: bosh-softlayer-tools
    type: git
    source:
      branch: container_based_stemcell_pipeline
      uri: https://github.com/bluebosh/bosh-softlayer-tools

  - name: bosh-softlayer-tools-master
    type: git
    source:
      branch: master
      uri: https://github.com/bluebosh/bosh-softlayer-tools

  - name: syslog-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/syslog-release

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh-softlayer-cpi-release

  #
  # SoftLayer
  #

  - name: softlayer-xen-ubuntu-trusty
    type: s3
    source:
      bucket: {{candidate-stemcell-bucket}}
      regexp: bosh-stemcell-(.+)-softlayer-esxi-ubuntu-trusty-go_agent.tgz
      access_key_id: {{stemcell-aws-access-key}}
      secret_access_key: {{stemcell-aws-secret-key}}

  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/bluebosh/bosh-deployment
      branch: softlayer

  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-softlayer-linux-amd64
      bucket: bosh-softlayer-artifacts

  - name: bats
    type: git
    source:
      uri: https://github.com/bluebosh/bosh-acceptance-tests.git
      branch: bluemix

  - name: environment
    type: pool
    source:
      pool: softlayer
      uri: git@github.com:bluebosh/bats-concourse-pool.git
      branch: master
      private_key: {{github_private_key}}

  - name: published-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
      tarball: false

  - name: stemcell-cmds
    type: s3
    source:
      bucket: bosh-softlayer-artifacts
      regexp: sl_stemcells-(.*)

  - name: light-softlayer-stemcell
    type: s3
    source:
      bucket: {{candidate-stemcell-bucket}}
      regexp: light-bosh-stemcell-(.*)-softlayer-(.*).tgz
      access_key_id: {{stemcell-aws-access-key}}
      secret_access_key: {{stemcell-aws-secret-key}}

  - name: light-softlayer-stemcell-prod
    type: s3
    source:
      bucket: {{published-stemcell-bucket}}
      regexp: light-bosh-stemcell-(.*)-softlayer-(.*).tgz
      access_key_id: {{stemcell-aws-access-key}}
      secret_access_key: {{stemcell-aws-secret-key}}

  #
  # Automation-test
  #

  - name: cf-deployment-softlayer
    type: git
    source:
      uri: https://github.com/bluebosh/cf-deployment
      branch: softlayer

  - name: director-artifacts
    type: s3
    source:
      bucket: {{automation-cf-bucket}}
      versioned_file: director_artifacts.tgz
      access_key_id: {{stemcell-aws-access-key}}
      secret_access_key: {{stemcell-aws-secret-key}}

  - name: cf-artifacts
    type: s3
    source:
      bucket: {{automation-cf-bucket}}
      versioned_file: cf-artifacts.tgz
      access_key_id: {{stemcell-aws-access-key}}
      secret_access_key: {{stemcell-aws-secret-key}}

  - name: os-conf-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/os-conf-release

  - name: stemcells-index
    type: git
    source:
      uri: git@github.com:bosh-io/stemcells-softlayer-index.git
      branch: master
      private_key: {{boshio_private_key}}