resources:
  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1

  - name: pipeline-src
    type: git
    source:
      uri: https://github.com/bluebosh/bosh-linux-stemcell-builder.git
      branch: compiled-release

  - name: bosh-softlayer-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh-softlayer-cpi-release

  #
  # releases to compile
  #
  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  #
  # stemcells to compile on
  #

  - name: light-stemcell
    type: s3
    source:
      regexp: light-bosh-stemcell-(\d+\.\d+\.\d+)-bluemix-xen-ubuntu-trusty-go_agent\.tgz
      bucket: bosh-softlayer-stemcells-bluemix

  - name: version
    type: semver
    source:
      driver: s3
      key: {{build_version}}
      bucket: {{candidate-custom-bluemix-stemcell-bucket}}
      access_key_id: {{stemcell-sl-os-access-key}}
      secret_access_key: {{stemcell-sl-os-secret-key}}
      endpoint: {{stemcell-sl-os-endpoint}}

  - name: director-state
    type: s3
    source:
      bucket: {{candidate-custom-bluemix-stemcell-bucket}}
      access_key_id: {{stemcell-sl-os-access-key}}
      secret_access_key: {{stemcell-sl-os-secret-key}}
      endpoint: {{stemcell-sl-os-endpoint}}
      regexp: director-state/director-state-(.*).tgz

  - name: compiled-release
    type: s3
    source:
      bucket: {{candidate-custom-bluemix-stemcell-bucket}}
      access_key_id: {{stemcell-sl-os-access-key}}
      secret_access_key: {{stemcell-sl-os-secret-key}}
      endpoint: {{stemcell-sl-os-endpoint}}
      regexp: compiled-release/compiled-release-allinone-(.*).tgz

  - name: compiled-deploy
    type: s3
    source:
      bucket: {{candidate-custom-bluemix-stemcell-bucket}}
      access_key_id: {{stemcell-sl-os-access-key}}
      secret_access_key: {{stemcell-sl-os-secret-key}}
      endpoint: {{stemcell-sl-os-endpoint}}
      regexp: compiled-deploy/compiled-deploy-(.*).yml

jobs:
  - name: prepare-director
    plan:
      - aggregate:
          - get: version
            params:
            bump: minor
          - get: pipeline-src
          - get: bosh-release
          - get: bosh-softlayer-cpi-release
          - get: light-stemcell
          - get: bosh-cli
      - task: deploy-director
        file: pipeline-src/ci/tasks/compiled-release/create-bosh-env.yml
        input_mapping:
          stemcell: light-stemcell
        params:
          BUILD_VERSION: {{build_version}}
          SL_USERNAME: {{softlayer_username}}
          SL_API_KEY: {{softlayer_api_key}}
          SL_DATACENTER: {{softlayer_datacenter}}
          SL_VLAN_PUBLIC: {{softlayer_vlan_public}}
          SL_VLAN_PRIVATE: {{softlayer_vlan_private}}
          SL_VM_PREFIX: {{softlayer_director_name_prefix}}
      - put: director-state
        params:
          file: director-state/director-state-*.tgz
          acl: public-read
      - put: version
        params:
          file: version/number

  - name: export-compiled-release
    plan:
      - aggregate:
          - get: pipeline-src
            trigger: true
          - get: light-stemcell
            trigger: true
          - get: bosh-cli
            trigger: true
          - get: director-state
            trigger: true
            passed: [prepare-director]
      - task: export-compiled-release
        file: pipeline-src/ci/tasks/compiled-release/export-compiled-release.yml
        input_mapping:
          stemcell: light-stemcell
        params:
          BUILD_VERSION: {{build_version}}
          SL_USERNAME: {{softlayer_username}}
          SL_API_KEY: {{softlayer_api_key}}
          SL_DATACENTER: {{softlayer_datacenter}}
          SL_VLAN_PUBLIC: {{softlayer_vlan_public}}
          SL_VLAN_PRIVATE: {{softlayer_vlan_private}}
          SL_VM_PREFIX: {{softlayer_director_name_prefix}}
          cf_release: {{cf_release}}
          cf_release_version: {{cf_release_version}}
          cf_release_location: {{cf_release_location}}
          cf_services_release: {{cf_services_release}}
          cf_services_release_version: {{cf_services_release_version}}
          cf_services_release_location: {{cf_services_release_location}}
          cf_services_contrib_release: {{cf_services_contrib_release}}
          cf_services_contrib_release_version: {{cf_services_contrib_release_version}}
          cf_services_contrib_release_location: {{cf_services_contrib_release_location}}
          mod_vms_release: {{mod_vms_release}}
          mod_vms_release_version: {{mod_vms_release_version}}
          mod_vms_release_location: {{mod_vms_release_location}}
          security_release: {{security_release}}
          security_release_version: {{security_release_version}}
          security_release_location: {{security_release_location}}
          admin_ui_release: {{admin_ui_release}}
          admin_ui_release_version: {{admin_ui_release_version}}
          admin_ui_release_location: {{admin_ui_release_location}}
          habr_release: {{habr_release}}
          habr_release_version: {{habr_release_version}}
          habr_release_location: {{habr_release_location}}
          loginserver_release: {{loginserver_release}}
          loginserver_release_version: {{loginserver_release_version}}
          loginserver_release_location: {{loginserver_release_location}}
          marmot_logstash_forwarder_release: {{marmot_logstash_forwarder_release}}
          marmot_logstash_forwarder_release_version: {{marmot_logstash_forwarder_release_version}}
          marmot_logstash_forwarder_release_location: {{marmot_logstash_forwarder_release_location}}
          unbound_release: {{unbound_release}}
          unbound_release_version: {{unbound_release_version}}
          unbound_release_location: {{unbound_release_location}}
      - put: compiled-release
        params:
          file: compiled-release/compiled-release-allinone-*.tgz
          acl: public-read
      - put: compiled-deploy
        params:
          file: compiled-deploy/compiled-deploy-*.yml
          acl: public-read

#        ensure:
#          do:
#          - task: teardown
#            file: pipeline-src/ci/pipelines/compiled-releases/tasks/bluemix/delete-bosh-env.yml
#            params:
#              SL_USERNAME: {{softlayer_username}}
#              SL_API_KEY: {{softlayer_api_key}}
#              SL_DATACENTER: {{softlayer_datacenter}}
#              SL_VLAN_PUBLIC: {{softlayer_vlan_public}}
#              SL_VLAN_PRIVATE: {{softlayer_vlan_private}}
#              SL_VM_PREFIX: {{softlayer_director_name_prefix}}

  - name: clean-deploy
    plan:
      - aggregate:
          - get: pipeline-src
          - get: bosh-cli
          - get: director-state
            trigger: true
            passed: [export-compiled-release]
      - task: teardown
        file: pipeline-src/ci/tasks/compiled-release/delete-compiled-deploy.yml
        params:
          BUILD_VERSION: {{build_version}}

  - name: upload-compiled-release
    plan:
      - aggregate:
          - get: pipeline-src
          - get: bosh-cli
          - get: director-state
          - get: compiled-release
            passed: [export-compiled-release]
      - task: upload-compiled-release
        file: pipeline-src/ci/tasks/compiled-release/upload-compiled-release.yml
        params:
          BUILD_VERSION: {{build_version}}
          FILE_W3_BOSH_PEM: {{file_w3_bosh_pem}}

  - name: verify-compiled-cf-deploy
    plan:
      - aggregate:
          - get: pipeline-src
          - get: bosh-cli
          - get: light-stemcell
          - get: director-state
            passed: [clean-deploy]
          - get: compiled-release
            trigger: true
            passed: [export-compiled-release]
          - get: compiled-deploy
            trigger: true
            passed: [export-compiled-release]
      - task: verify-compiled-cf-release
        file: pipeline-src/ci/tasks/compiled-release/verify-compiled-cf-deploy.yml
        input_mapping:
          stemcell: light-stemcell
        params:
          BUILD_VERSION: {{build_version}}
          SL_USERNAME: {{softlayer_username}}
          SL_API_KEY: {{softlayer_api_key}}
          SL_DATACENTER: {{softlayer_datacenter}}
          SL_VLAN_PUBLIC: {{softlayer_vlan_public}}
          SL_VLAN_PRIVATE: {{softlayer_vlan_private}}
          SL_VM_PREFIX: {{softlayer_director_name_prefix}}
          cf_release: {{cf_release}}
          cf_release_version: {{cf_release_version}}
          cf_release_location: {{cf_release_location}}
          cf_services_release: {{cf_services_release}}
          cf_services_release_version: {{cf_services_release_version}}
          cf_services_release_location: {{cf_services_release_location}}
          cf_services_contrib_release: {{cf_services_contrib_release}}
          cf_services_contrib_release_version: {{cf_services_contrib_release_version}}
          cf_services_contrib_release_location: {{cf_services_contrib_release_location}}
          mod_vms_release: {{mod_vms_release}}
          mod_vms_release_version: {{mod_vms_release_version}}
          mod_vms_release_location: {{mod_vms_release_location}}
          security_release: {{security_release}}
          security_release_version: {{security_release_version}}
          security_release_location: {{security_release_location}}
          admin_ui_release: {{admin_ui_release}}
          admin_ui_release_version: {{admin_ui_release_version}}
          admin_ui_release_location: {{admin_ui_release_location}}
          habr_release: {{habr_release}}
          habr_release_version: {{habr_release_version}}
          habr_release_location: {{habr_release_location}}
          loginserver_release: {{loginserver_release}}
          loginserver_release_version: {{loginserver_release_version}}
          loginserver_release_location: {{loginserver_release_location}}
          marmot_logstash_forwarder_release: {{marmot_logstash_forwarder_release}}
          marmot_logstash_forwarder_release_version: {{marmot_logstash_forwarder_release_version}}
          marmot_logstash_forwarder_release_location: {{marmot_logstash_forwarder_release_location}}
          unbound_release: {{unbound_release}}
          unbound_release_version: {{unbound_release_version}}
          unbound_release_location: {{unbound_release_location}}

  - name: delete-compiled-deploy
    plan:
      - aggregate:
          - get: pipeline-src
          - get: bosh-cli
          - get: director-state
          - get: compiled-deploy
            trigger: true
            passed: [verify-compiled-cf-deploy]
      - task: teardown
        file: pipeline-src/ci/tasks/compiled-release/delete-compiled-deploy.yml
        params:
          BUILD_VERSION: {{build_version}}

  - name: delete-bosh-env
    plan:
      - aggregate:
          - get: pipeline-src
          - get: bosh-cli
          - get: director-state
            passed: [delete-compiled-deploy]
      - task: teardown
        file: pipeline-src/ci/tasks/compiled-release/delete-bosh-env.yml
        params:
          BUILD_VERSION: {{build_version}}
          SL_USERNAME: {{softlayer_username}}
          SL_API_KEY: {{softlayer_api_key}}
          SL_DATACENTER: {{softlayer_datacenter}}
          SL_VLAN_PUBLIC: {{softlayer_vlan_public}}
          SL_VLAN_PRIVATE: {{softlayer_vlan_private}}
          SL_VM_PREFIX: {{softlayer_director_name_prefix}}