---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/cpi-certification

inputs:
  - name: bosh-linux-stemcell-builder-master
    path: bosh-linux-stemcell-builder
  - name: stemcell
  - name: version
outputs:
  - name: light-bluemix-stemcell-prod
  - name: version-tag

run:
  path: bosh-linux-stemcell-builder/ci/bluemix/tasks/copy-artifacts.sh

params:
  AWS_ACCESS_KEY_ID:     required
  AWS_SECRET_ACCESS_KEY: required
  AWS_DEFAULT_REGION:    us-east-1
  CANDIDATE_BUCKET_NAME: required