---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/aws-cpi-release

inputs:
  - name: version
  - name: bosh-linux-stemcell-builder-master
    path: bosh-linux-stemcell-builder

run:
  path: bosh-linux-stemcell-builder/ci/bluemix/tasks/post-stemcell-checksum.sh

params:
  BOSHIO_TOKEN:           replace-me
  PUBLISHED_BUCKET_NAME:  replace-me