---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/cpi-certification

inputs:
  - name: light-bluemix-stemcell-prod
    path: stemcell
  - name: bosh-linux-stemcell-builder-master
    path: bosh-linux-stemcell-builder

outputs:
  - name: replaced

run:
  path: bosh-linux-stemcell-builder/ci/bluemix/tasks/replace-stemcell-artifacts.sh
